<script>
  function get(url) {
    // Return a new promise.
    return new Promise((resolve, reject) => {
      // Do the usual XHR stuff
      const req = new XMLHttpRequest();

      req.open('GET', url);

      req.addEventListener('load', (e) => {
        const xhr = e.target;

        // This is called even on 404 etc
        // so check the status
        if (xhr.status >= 200 && xhr.status < 300) {
          // Resolve the promise with the response text
          resolve(xhr.response);
        }
        else {
          // Otherwise reject with the status text
          // which will hopefully be a meaningful error
          reject(Error(xhr.statusText));
        }
      });

      // Handle network errors
      req.addEventListener('error', () => {
        reject(Error('Network Error'));
      });

      // Make the request
      req.send();
    });
  }

  // Usage
  get('../jsons/story.json')
    .then((response) => {
      console.log('Success!', JSON.parse(response));
    })
    .catch((error) => {
      console.error('Failed!', error);
    });

</script>
